dist: trusty
sudo: required
group: deprecated-2017Q4
git:
  depth: 3
env:
  global:
  - secure: "MhcV5a3N8vrJ68sLcqQkH9F/gN2r2ibNM2y7yrt+mJ9N5WLl9bdzIEWyUD4AAwBk6Rf9BTQ25utpbWIlPLo2rwChh4yldGA/PQF3IJju4nlJLuVjX9XPk9PEZLYbwQGumMiRb0TonwvNNG5SyrM+mu/YT3oDKwykLtTG4lz3p14="
  - secure: "CqpA+9sezpt3BXRuocToa9dDTOMEpg08XCy9WX73PbfoDHFEPXSEboY46VhbX4p3KJeRZ2Go5zQS5pPB7+CubMMKmb1xmo1pnHtmWemnnfHzSRPEM27wMokNkYLY8jIRcZkdJpZHWjGWV4fzr6cDMg3t22gzOB+eUnGCLa7Ziqo="
language: c
compiler: gcc

addons:
  apt:
#    sources:
#    - ubuntu-toolchain-r-test
    packages:
#    - gcc-7
    - cmake
    - cmake-data
    - gcc-aarch64-linux-gnu
    - g++-aarch64-linux-gnu

before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- sudo sed -i 's/deb http/deb [arch=amd64,i386] http/' /etc/apt/sources.list
- cat /etc/apt/sources.list
- sudo grep "ubuntu.com/ubuntu" /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list
- sudo sed -i 's/amd64,i386/armhf,arm64/' /etc/apt/sources.list.d/ports.list
- sudo sed -i 's#http://.*/ubuntu#http://ports.ubuntu.com/ubuntu-ports#' /etc/apt/sources.list.d/ports.list
- cat /etc/apt/sources.list.d/ports.list
- sudo dpkg --add-architecture armhf
- sudo apt-get update || true
#16.04+ - sudo apt-get -yq --no-install-suggests --no-install-recommends install libwayland-bin:amd64 -o Dpkg::Options::="--force-overwrite"
#14.04 has /usr/bin/wayland-scanner in libwayland-dev, install amd64, copy bin, replace with armhf
#when transitioning to 16.04 can simply install libwayland-bin:amd64
- sudo apt-get -yq --no-install-suggests --no-install-recommends install libwayland-dev:amd64 -o Dpkg::Options::="--force-overwrite"
- sudo cp /usr/bin/wayland-scanner /usr/bin/wayland-scanner.tmp
- sudo apt-get -yq --no-install-suggests --no-install-recommends install libxrandr-dev:arm64 libxinerama-dev:arm64 libxcursor-dev:arm64 libxi-dev:arm64 libwayland-dev:arm64 libxkbcommon-dev:arm64 libegl1-mesa-dev:arm64 -o Dpkg::Options::="--force-overwrite"
- sudo cp /usr/bin/wayland-scanner.tmp /usr/bin/wayland-scanner

script:
- mkdir build
- cd build
- wget https://mirrors.kernel.org/ubuntu/pool/universe/e/extra-cmake-modules/extra-cmake-modules_5.38.0a-0ubuntu1_amd64.deb
- sudo dpkg -i extra-cmake-modules_5.38.0a-0ubuntu1_amd64.deb
- git clone git://anongit.freedesktop.org/wayland/wayland-protocols
- pushd wayland-protocols;
- git checkout 1.15 && ./autogen.sh --prefix=/usr && make && sudo make install;
- popd;
#- CC="gcc-7" cmake -DGLFW_USE_WAYLAND=ON -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" -DCMAKE_SHARED_LINKER_FLAGS=-Wl,--wrap,memcpy ..
- CC="aarch64-linux-gnu-gcc" cmake -DGLFW_USE_WAYLAND=ON -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" -DCMAKE_SHARED_LINKER_FLAGS=-Wl,--wrap,memcpy ..
- cmake --build .
- cd src
- aarch64-linux-gnu-strip libglfw.so
- "aws s3 cp libglfw.so s3://build.lwjgl.org/nightly/linux/arm64/libglfw_wayland.so --acl public-read --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
- "git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git"
- "aws s3 cp revision.git s3://build.lwjgl.org/nightly/linux/arm64/libglfw_wayland.so.git --acl public-read --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""