dist: trusty
sudo: true
git:
  depth: 3
env:
  global:
  - secure: "MhcV5a3N8vrJ68sLcqQkH9F/gN2r2ibNM2y7yrt+mJ9N5WLl9bdzIEWyUD4AAwBk6Rf9BTQ25utpbWIlPLo2rwChh4yldGA/PQF3IJju4nlJLuVjX9XPk9PEZLYbwQGumMiRb0TonwvNNG5SyrM+mu/YT3oDKwykLtTG4lz3p14="
  - secure: "CqpA+9sezpt3BXRuocToa9dDTOMEpg08XCy9WX73PbfoDHFEPXSEboY46VhbX4p3KJeRZ2Go5zQS5pPB7+CubMMKmb1xmo1pnHtmWemnnfHzSRPEM27wMokNkYLY8jIRcZkdJpZHWjGWV4fzr6cDMg3t22gzOB+eUnGCLa7Ziqo="
language: c
compiler: gcc

addons:
  apt:
#    sources:
#    - ubuntu-toolchain-r-test
    packages:
#    - gcc-7
    - cmake
    - cmake-data
    - gcc-arm-linux-gnueabihf
    - g++-arm-linux-gnueabihf
    - libxrandr-dev:armhf
    - libxinerama-dev:armhf
    - libxcursor-dev:armhf
    - libxi-dev:armhf

before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- sed -i 's/deb http/deb [arch=amd64,i386] http/' /etc/apt/sources.list
- cp /etc/apt/sources.list /etc/apt/sources.list.d/ports.list
- sed -i 's/amd64,i386/armhf,arm64/' /etc/apt/sources.list.d/ports.list
- sed -i 's#http://.*/ubuntu#http://ports.ubuntu.com/ubuntu-ports#' /etc/apt/sources.list.d/ports.list
- dpkg --add-architecture armhf
- apt update

script:
- mkdir build
- cd build
#- CC="gcc-7" cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" -DCMAKE_SHARED_LINKER_FLAGS=-Wl,--wrap,memcpy ..
- CC="arm-linux-gnueabihf-gcc" cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" -DCMAKE_SHARED_LINKER_FLAGS=-Wl,--wrap,memcpy ..
- cmake --build .
- cd src
- arm-linux-gnueabihf-strip libglfw.so
- file libglfw.so*
#- "aws s3 cp libglfw.so s3://build.lwjgl.org/nightly/linux/x64/ --acl public-read --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
#- "git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git"
#- "aws s3 cp revision.git s3://build.lwjgl.org/nightly/linux/x64/libglfw.so.git --acl public-read --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""